% validate_hdl.m
% Compare HDL DFE output against MATLAB reference and report BER.
%
% Expects the following files to exist (generated by export_vectors.m and
% the HDL simulation):
%   ../vectors/channel_out.hex       (written by export_vectors.m)
%   ../vectors/tx_bits.txt           (written by export_vectors.m)
%   ../vectors/hdl_decisions.txt     (written by tb_dfe.sv simulation)
%
% Parameters MUST match export_vectors.m and tb_dfe.sv.

clear; clc;
addpath(fileparts(mfilename('fullpath')));   % make sure matlab/ is on path

%% ---- Parameters (keep in sync with export_vectors.m / tb_dfe.sv) -------
N        = 2000;
h        = [1.0, 0.5, -0.2];
EbN0_dB  = 12;
seed     = 101;
sps      = 8;

%% ---- Re-run channel with the same seed -> identical sequence ------------
[x, y_clean, ~] = isi_channel_model(N, h, 0, seed, sps);
y_noisy          = awgn_noise(y_clean, EbN0_dB);

sample_idx = floor(sps / 2);
rx_sym     = y_noisy(sample_idx : sps : end);
rx_sym     = rx_sym(1:N);

%% ---- No-equaliser BER --------------------------------------------------
d_raw            = sign(rx_sym);
d_raw(d_raw==0)  = 1;           % tie -> +1 (matches slicer behaviour)
ber_raw          = ber_measure(x, d_raw);

%% ---- MATLAB DFE reference BER -----------------------------------------
dfe_coeffs        = h(2:end);
[d_matlab, ~]     = dfe_reference(rx_sym, dfe_coeffs);
ber_matlab        = ber_measure(x, d_matlab);

%% ---- MATLAB fixed-point (RTL-equivalent) reference ---------------------
FRAC_BITS   = 11;                    % Q4.11 format from export_vectors.m
SCALE       = 2^FRAC_BITS;
rx_q        = round(rx_sym * SCALE);
rx_q        = max(min(rx_q, 32767), -32768);

coeffs_q15  = round(dfe_coeffs * 2^15);
coeffs_q15  = max(min(coeffs_q15, 32767), -32768);

[d_fixed, ~] = dfe_reference_fixed(rx_q, coeffs_q15, FRAC_BITS);
ber_fixed    = ber_measure(x, d_fixed);

%% ---- HDL DFE BER -------------------------------------------------------
script_dir   = fileparts(mfilename('fullpath'));
script_root  = fileparts(script_dir);

candidate_dirs = {
    fullfile(script_root, 'vectors')
    fullfile(pwd, 'vectors')
    fullfile(pwd, '..', 'vectors')
    fullfile(fileparts(pwd), 'vectors')
};

vectors_dir = '';
hdl_file    = '';
for c = 1:numel(candidate_dirs)
    candidate_file = fullfile(candidate_dirs{c}, 'hdl_decisions.txt');
    if isfile(candidate_file)
        vectors_dir = candidate_dirs{c};
        hdl_file    = candidate_file;
        break;
    end
end

if isempty(hdl_file)
    searched = strjoin(candidate_dirs, newline);
    error('HDL decisions file not found. Searched:\n%s\nRun the ModelSim/Questa simulation first.', searched);
end

hdl_raw      = readmatrix(hdl_file, 'FileType', 'text');

% Ensure we compare exactly N scalar symbols and avoid row/column mismatch.
hdl_raw      = hdl_raw(:);
if numel(hdl_raw) < N
    error('HDL decisions file has %d entries, expected at least %d.', numel(hdl_raw), N);
end
hdl_raw      = hdl_raw(1:N);
if any((hdl_raw ~= 0) & (hdl_raw ~= 1))
    error('HDL decisions file must contain only 0/1 values.');
end

d_hdl        = 2 * hdl_raw - 1;   % 0->-1, 1->+1
ber_hdl      = ber_measure(x, d_hdl);

%% ---- Report ------------------------------------------------------------
fprintf('=== BER Summary  (Eb/N0 = %.1f dB,  N = %d bits) ===\n', EbN0_dB, N);
fprintf('  No equaliser : %6.4f   (%4d errors)\n', ber_raw,    round(ber_raw    * N));
fprintf('  MATLAB DFE   : %6.4f   (%4d errors)\n', ber_matlab, round(ber_matlab * N));
fprintf('  MATLAB Fixed : %6.4f   (%4d errors)\n', ber_fixed,  round(ber_fixed  * N));
fprintf('  HDL DFE      : %6.4f   (%4d errors)\n', ber_hdl,    round(ber_hdl    * N));
fprintf('\n');

% Extra diagnostics to classify common RTL mismatches.
ber_hdl_inv = ber_measure(x, -d_hdl);
ber_hdl_d1  = ber_measure(x(2:end), d_hdl(1:end-1));
ber_hdl_u1  = ber_measure(x(1:end-1), d_hdl(2:end));
fprintf('  HDL inverted : %6.4f\n', ber_hdl_inv);
fprintf('  HDL delay +1 : %6.4f\n', ber_hdl_d1);
fprintf('  HDL lead  -1 : %6.4f\n', ber_hdl_u1);
fprintf('\n');

%% ---- Pass/fail ---------------------------------------------------------
err_diff_float = abs(round(ber_hdl * N) - round(ber_matlab * N));
err_diff_fixed = abs(round(ber_hdl * N) - round(ber_fixed  * N));

tol_fixed = max(1, round(0.05 * round(ber_fixed * N)));
if err_diff_fixed == 0
    fprintf('PASS: HDL and MATLAB fixed-point reference error counts match exactly.\n');
elseif err_diff_fixed <= tol_fixed
    fprintf('PASS (within 5%%): HDL error count within tolerance of MATLAB fixed-point reference.\n');
else
    fprintf('FAIL: HDL error count differs from MATLAB fixed-point reference by %d errors.\n', err_diff_fixed);
    fprintf('      Check coefficient packing order and feedback latency.\n');
end

fprintf('Delta vs MATLAB float ref : %d errors\n', err_diff_float);
fprintf('Delta vs MATLAB fixed ref : %d errors\n', err_diff_fixed);

if err_diff_fixed < err_diff_float
    fprintf('Note: fixed-point reference tracks HDL better than floating-point reference.\n');
end
